export const LISTRECIPES = [
  {
    idMeal: '52878',
    strMeal: 'Beef and Oyster pie',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'British',
    strInstructions:
      'Season the beef cubes with salt and black pepper. Heat a tablespoon of oil in the frying pan and fry the meat over a high heat. Do this in three batches so that you don’t overcrowd the pan, transferring the meat to a large flameproof casserole dish once it is browned all over. Add extra oil if the pan seems dry.\r\nIn the same pan, add another tablespoon of oil and cook the shallots for 4-5 minutes, then add the garlic and fry for 30 seconds. Add the bacon and fry until slightly browned. Transfer the onion and bacon mixture to the casserole dish and add the herbs.\r\nPreheat the oven to 180C/350F/Gas 4.\r\nPour the stout into the frying pan and bring to the boil, stirring to lift any stuck-on browned bits from the bottom of the pan. Pour the stout over the beef in the casserole dish and add the stock. Cover the casserole and place it in the oven for 1½-2 hours, or until the beef is tender and the sauce is reduced.\r\nSkim off any surface fat, taste and add salt and pepper if necessary, then stir in the cornflour paste. Put the casserole dish on the hob – don’t forget that it will be hot – and simmer for 1-2 minutes, stirring, until thickened. Leave to cool.\r\nIncrease the oven to 200C/400F/Gas 6. To make the pastry, put the flour and salt in a very large bowl. Grate the butter and stir it into the flour in three batches. Gradually add 325ml/11fl oz cold water – you may not need it all – and stir with a round-bladed knife until the mixture just comes together. Knead the pastry lightly into a ball on a lightly floured surface and set aside 250g/9oz for the pie lid.\r\nRoll the rest of the pastry out until about 2cm/¾in larger than the dish you’re using. Line the dish with the pastry then pile in the filling, tucking the oysters in as well. Brush the edge of the pastry with beaten egg.\r\nRoll the remaining pastry until slightly larger than your dish and gently lift over the filling, pressing the edges firmly to seal, then trim with a sharp knife. Brush with beaten egg to glaze. Put the dish on a baking tray and bake for 25-30 minutes, or until the pastry is golden-brown and the filling is bubbling.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg',
    strTags: 'Pie',
    strYoutube: 'https://www.youtube.com/watch?v=ONX74yP6JnI',
    strIngredient1: 'Beef',
    strIngredient2: 'Olive Oil',
    strIngredient3: 'Shallots',
    strIngredient4: 'Garlic',
    strIngredient5: 'Bacon',
    strIngredient6: 'Thyme',
    strIngredient7: 'Bay Leaf',
    strIngredient8: 'Stout',
    strIngredient9: 'Beef Stock',
    strIngredient10: 'Corn Flour',
    strIngredient11: 'Oysters',
    strIngredient12: 'Plain Flour',
    strIngredient13: 'Salt',
    strIngredient14: 'Butter',
    strIngredient15: 'Eggs',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '900g',
    strMeasure2: '3 tbs',
    strMeasure3: '3',
    strMeasure4: '2 cloves minced',
    strMeasure5: '125g',
    strMeasure6: '1 tbs chopped',
    strMeasure7: '2',
    strMeasure8: '330ml',
    strMeasure9: '400ml',
    strMeasure10: '2 tbs',
    strMeasure11: '8',
    strMeasure12: '400g',
    strMeasure13: 'pinch',
    strMeasure14: '250g',
    strMeasure15: 'To Glaze',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbc.co.uk/food/recipes/beef_and_oyster_pie_65230',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52878.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '224',
      '289',
      '149',
      '14',
      '313',
      '20',
      '450',
      '26',
      '354',
      '449',
      '248',
      '281',
      '41',
      '123',
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53071',
    strMeal: 'Beef Asado',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Filipino',
    strInstructions:
      '0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=lNlK8DVhXXA',
    strIngredient1: 'Beef',
    strIngredient2: 'Beef Stock Concentrate',
    strIngredient3: 'Tomato Puree',
    strIngredient4: 'Water',
    strIngredient5: 'Soy Sauce',
    strIngredient6: 'White Wine Vinegar',
    strIngredient7: 'Pepper',
    strIngredient8: 'Bay Leaf',
    strIngredient9: 'Lemon',
    strIngredient10: 'Tomato Sauce',
    strIngredient11: 'Butter',
    strIngredient12: 'Olive Oil',
    strIngredient13: 'Onion',
    strIngredient14: 'Garlic',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1.5kg',
    strMeasure2: '1',
    strMeasure3: '8 ounces',
    strMeasure4: '3 cups ',
    strMeasure5: '6 tablespoons',
    strMeasure6: '1 tbs',
    strMeasure7: '2 tbs',
    strMeasure8: '4',
    strMeasure9: '1/2 ',
    strMeasure10: '2 tbs',
    strMeasure11: '3 tbs',
    strMeasure12: '1/2 cup ',
    strMeasure13: '1 chopped',
    strMeasure14: '4 cloves',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://panlasangpinoy.com/beef-asado/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53071.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '573',
      '316',
      '333',
      '296',
      '541',
      '244',
      '20',
      '197',
      '399',
      '41',
      '224',
      '364',
      '149',
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52769',
    strMeal: 'Kapsalon',
    strDrinkAlternate: null,
    strCategory: 'Lamb',
    strArea: 'Dutch',
    strInstructions:
      "Cut the meat into strips. Heat oil in a pan and fry the strips for 6 minutes until it's ready.\r\nBake the fries until golden brown in a deep fryrer. When ready transfer to a backing dish. Make sure the fries are spread over the whole dish.\r\nCover the fries with a new layer of meat and spread evenly.\r\nAdd a layer of cheese over the meat. You can also use grated cheese. When done put in the oven for a few minutes until the cheese is melted.\r\nChop the lettuce, tomato and cucumber in small pieces and mix together. for a basic salad. As extra you can add olives jalapenos and a red union.\r\nDived the salad over the dish and Serve with garlicsauce and hot sauce",
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg',
    strTags: 'Snack',
    strYoutube: 'https://www.youtube.com/watch?v=UIcuiU1kV8I',
    strIngredient1: 'Fries',
    strIngredient2: 'Doner Meat',
    strIngredient3: 'Garlic sauce',
    strIngredient4: 'Hotsauce',
    strIngredient5: 'Lettuce',
    strIngredient6: 'Tomato',
    strIngredient7: 'Cucumber',
    strIngredient8: 'Gouda cheese',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '250 Grams',
    strMeasure2: '500 Grams',
    strMeasure3: 'Topping',
    strMeasure4: 'Topping',
    strMeasure5: '1 Bulb',
    strMeasure6: '1',
    strMeasure7: '3rd',
    strMeasure8: '100 Grams',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52769.png',
    idCategory: '4',
    idIngredients: [
      '146',
      '114',
      '152',
      '180',
      '201',
      '365',
      '103',
      '159',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52904',
    strMeal: 'Beef Bourguignon',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'French',
    strInstructions:
      'Heat a large casserole pan and add 1 tbsp goose fat. Season the beef and fry until golden brown, about 3-5 mins, then turn over and fry the other side until the meat is browned all over, adding more fat if necessary. Do this in 2-3 batches, transferring the meat to a colander set over a bowl when browned.\r\nIn the same pan, fry the bacon, shallots or pearl onions, mushrooms, garlic and bouquet garni until lightly browned. Mix in the tomato purée and cook for a few mins, stirring into the mixture. This enriches the bourguignon and makes a great base for the stew. Then return the beef and any drained juices to the pan and stir through.\r\nPour over the wine and about 100ml water so the meat bobs up from the liquid, but isn’t completely covered. Bring to the boil and use a spoon to scrape the caramelised cooking juices from the bottom of the pan – this will give the stew more flavour.\r\nHeat oven to 150C/fan 130C/gas 2. Make a cartouche: tear off a square of foil slightly larger than the casserole, arrange it in the pan so it covers the top of the stew and trim away any excess foil. Then cook for 3 hrs. If the sauce looks watery, remove the beef and veg with a slotted spoon, and set aside. Cook the sauce over a high heat for a few mins until the sauce has thickened a little, then return the beef and vegetables to the pan.\r\nTo make the celeriac mash, peel the celeriac and cut into cubes. Heat the olive oil in a large frying pan. Tip in the celeriac and fry for 5 mins until it turns golden. Season well with salt and pepper. Stir in the rosemary, thyme, bay and cardamom pods, then pour over 200ml water, enough to nearly cover the celeriac. Turn the heat to low, partially cover the pan and leave to simmer for 25-30 mins.\r\nAfter 25-30 mins, the celeriac should be soft and most of the water will have evaporated. Drain away any remaining water, then remove the herb sprigs, bay and cardamom pods. Lightly crush with a potato masher, then finish with a glug of olive oil and season to taste. Spoon the beef bourguignon into serving bowls and place a large spoonful of the celeriac mash on top. Garnish with one of the bay leaves, if you like.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=SQnr4Z-7rok',
    strIngredient1: 'Goose Fat',
    strIngredient2: 'Beef Shin',
    strIngredient3: 'Bacon',
    strIngredient4: 'Challots',
    strIngredient5: 'Chestnut Mushroom',
    strIngredient6: 'Garlic Clove',
    strIngredient7: 'Bouquet Garni',
    strIngredient8: 'Tomato Puree',
    strIngredient9: 'Red Wine',
    strIngredient10: 'Celeriac',
    strIngredient11: 'Olive Oil',
    strIngredient12: 'Thyme',
    strIngredient13: 'Rosemary',
    strIngredient14: 'Bay Leaf',
    strIngredient15: 'Cardamom',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '3 tsp',
    strMeasure2: '600g',
    strMeasure3: '100g ',
    strMeasure4: '350g',
    strMeasure5: '250g',
    strMeasure6: '2 sliced',
    strMeasure7: '1',
    strMeasure8: '1 tbs',
    strMeasure9: '750 ml ',
    strMeasure10: '600g',
    strMeasure11: '2 tbs',
    strMeasure12: 'sprigs of fresh',
    strMeasure13: 'sprigs of fresh',
    strMeasure14: '2',
    strMeasure15: '4',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52904.png',
    idCategory: '1',
    idIngredients: [
      '391',
      '484',
      '14',
      '57',
      '63',
      '150',
      '485',
      '316',
      '266',
      '54',
      '224',
      '313',
      '396',
      '20',
      '47',
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52873',
    strMeal: 'Beef Dumpling Stew',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'British',
    strInstructions:
      'Preheat the oven to 180C/350F/Gas 4.\r\n\r\nFor the beef stew, heat the oil and butter in an ovenproof casserole and fry the beef until browned on all sides.\r\n\r\nSprinkle over the flour and cook for a further 2-3 minutes.\r\n\r\nAdd the garlic and all the vegetables and fry for 1-2 minutes.\r\n\r\nStir in the wine, stock and herbs, then add the Worcestershire sauce and balsamic vinegar, to taste. Season with salt and freshly ground black pepper.\r\n\r\nCover with a lid, transfer to the oven and cook for about two hours, or until the meat is tender.\r\n\r\nFor the dumplings, sift the flour, baking powder and salt into a bowl.\r\nAdd the suet and enough water to form a thick dough.\r\n\r\nWith floured hands, roll spoonfuls of the dough into small balls.\r\n\r\nAfter two hours, remove the lid from the stew and place the balls on top of the stew. Cover, return to the oven and cook for a further 20 minutes, or until the dumplings have swollen and are tender. (If you prefer your dumplings with a golden top, leave the lid off when returning to the oven.)\r\n\r\nTo serve, place a spoonful of mashed potato onto each of four serving plates and top with the stew and dumplings. Sprinkle with chopped parsley.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg',
    strTags: 'Stew,Baking',
    strYoutube: 'https://www.youtube.com/watch?v=6NgheY-r5t0',
    strIngredient1: 'Olive Oil',
    strIngredient2: 'Butter',
    strIngredient3: 'Beef',
    strIngredient4: 'Plain Flour',
    strIngredient5: 'Garlic',
    strIngredient6: 'Onions',
    strIngredient7: 'Celery',
    strIngredient8: 'Carrots',
    strIngredient9: 'Leek',
    strIngredient10: 'Swede',
    strIngredient11: 'Red Wine',
    strIngredient12: 'Beef Stock',
    strIngredient13: 'Bay Leaf',
    strIngredient14: 'Thyme',
    strIngredient15: 'Parsley',
    strIngredient16: 'Plain Flour',
    strIngredient17: 'Baking Powder',
    strIngredient18: 'Suet',
    strIngredient19: 'Water',
    strIngredient20: null,
    strMeasure1: '2 tbs',
    strMeasure2: '25g',
    strMeasure3: '750g',
    strMeasure4: '2 tblsp ',
    strMeasure5: '2 cloves minced',
    strMeasure6: '175g',
    strMeasure7: '150g',
    strMeasure8: '150g',
    strMeasure9: '2 chopped',
    strMeasure10: '200g',
    strMeasure11: '150ml',
    strMeasure12: '500g',
    strMeasure13: '2',
    strMeasure14: '3 tbs',
    strMeasure15: '3 tblsp chopped',
    strMeasure16: '125g',
    strMeasure17: '1 tsp ',
    strMeasure18: '60g',
    strMeasure19: 'Splash',
    strMeasure20: '',
    strSource: 'https://www.bbc.co.uk/food/recipes/beefstewwithdumpling_87333',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52873.png',
    idCategory: '1',
    idIngredients: [
      '224',
      '41',
      '3',
      '248',
      '149',
      '227',
      '55',
      '49',
      '196',
      '447',
      '266',
      '26',
      '20',
      '313',
      '237',
      '248',
      '15',
      '446',
      '333',
      null,
    ],
  },
  {
    idMeal: '52952',
    strMeal: 'Beef Lo Mein',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Chinese',
    strInstructions:
      'STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.\r\nSTEP 2 - BOILING THE THE NOODLES\r\nIn a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.\r\nSTEP 3 - STIR FRY\r\nAdd 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.\r\nSet the cooked beef aside\r\nIn a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.\r\nAdd the noodles to wok\r\nTo make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.\r\nNext add the beef to wok and stir-fry',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=ZT9LSsNXXe0',
    strIngredient1: 'Beef',
    strIngredient2: 'Salt',
    strIngredient3: 'Pepper',
    strIngredient4: 'Sesame Seed Oil',
    strIngredient5: 'Egg',
    strIngredient6: 'Starch',
    strIngredient7: 'Oil',
    strIngredient8: 'Noodles',
    strIngredient9: 'Onion',
    strIngredient10: 'Minced Garlic',
    strIngredient11: 'Ginger',
    strIngredient12: 'Bean Sprouts',
    strIngredient13: 'Mushrooms',
    strIngredient14: 'Water',
    strIngredient15: 'Oyster Sauce',
    strIngredient16: 'Sugar',
    strIngredient17: 'Soy Sauce',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1/2 lb',
    strMeasure2: 'pinch',
    strMeasure3: 'pinch',
    strMeasure4: '2 tsp',
    strMeasure5: '1/2 ',
    strMeasure6: '3 tbs',
    strMeasure7: '5 tbs',
    strMeasure8: '1/4 lb',
    strMeasure9: '1/2 cup ',
    strMeasure10: '1 tsp ',
    strMeasure11: '1 tsp ',
    strMeasure12: '1 cup ',
    strMeasure13: '1 cup ',
    strMeasure14: '1 cup ',
    strMeasure15: '1 tbs',
    strMeasure16: '1 tsp ',
    strMeasure17: '1 tsp ',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://sueandgambo.com/pages/beef-lo-mein',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52952.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '281',
      '244',
      '443',
      '483',
      '528',
      '223',
      '534',
      '364',
      '212',
      '154',
      '533',
      '218',
      '333',
      '231',
      '305',
      '296',
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53068',
    strMeal: 'Beef Mechado',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Filipino',
    strInstructions:
      '0.\tMake the beef tenderloin marinade by combining soy sauce, vinegar, ginger, garlic, sesame oil, olive oil, sugar, salt, and ground black pepper in a large bowl. Mix well.\r\n1.\tAdd the cubed beef tenderloin to the bowl with the beef tenderloin marinade. Gently toss to coat the beef. Let it stay for 1 hour.\r\n2.\tUsing a metal or bamboo skewer, assemble the beef kebob by skewering the vegetables and marinated beef tenderloin.\r\n3.\tHeat-up the grill and start grilling the beef kebobs for 3 minutes per side. This will give you a medium beef that is juicy and tender on the inside. Add more time if you want your beef well done, but it will be less tender.\r\n4.\tTransfer to a serving plate. Serve with Saffron rice.\r\n5.\tShare and enjoy!\r\n',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg',
    strTags: 'Stew, Warming',
    strYoutube: 'https://www.youtube.com/watch?v=jxW3Lj8VjyE',
    strIngredient1: 'Garlic',
    strIngredient2: 'Onion',
    strIngredient3: 'Beef',
    strIngredient4: 'Tomato Puree',
    strIngredient5: 'Water',
    strIngredient6: 'Olive Oil',
    strIngredient7: 'Lemon',
    strIngredient8: 'Potatoes',
    strIngredient9: 'Soy Sauce',
    strIngredient10: 'Black Pepper',
    strIngredient11: 'Bay Leaves',
    strIngredient12: 'Salt',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '3 cloves',
    strMeasure2: '1 sliced',
    strMeasure3: '2 Lbs',
    strMeasure4: '8 ounces',
    strMeasure5: '1 cup ',
    strMeasure6: '3 tbs',
    strMeasure7: '1 Slice',
    strMeasure8: '1 large',
    strMeasure9: '1/4 cup',
    strMeasure10: '1/2 tsp',
    strMeasure11: '2',
    strMeasure12: 'To taste',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://panlasangpinoy.com/filipino-pinoy-food-tomato-sauce-beef-mechado-recipe/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53068.png',
    idCategory: '1',
    idIngredients: [
      '149',
      '364',
      '3',
      '316',
      '333',
      '224',
      '197',
      '253',
      '296',
      '29',
      '21',
      '281',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52812',
    strMeal: 'Beef Brisket Pot Roast',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'American',
    strInstructions:
      '1 Prepare the brisket for cooking: On one side of the brisket there should be a layer of fat, which you want. If there are any large chunks of fat, cut them off and discard them. Large pieces of fat will not be able to render out completely.\r\nUsing a sharp knife, score the fat in parallel lines, about 3/4-inch apart. Slice through the fat, not the beef. Repeat in the opposite direction to make a cross-hatch pattern.\r\nSalt the brisket well and let it sit at room temperature for 30 minutes.\r\n \r\n2 Sear the brisket: You\'ll need an oven-proof, thick-bottomed pot with a cover, or Dutch oven, that is just wide enough to hold the brisket roast with a little room for the onions.\r\nPat the brisket dry and place it, fatty side down, into the pot and place it on medium high heat. Cook for 5-8 minutes, lightly sizzling, until the fat side is nicely browned. (If the roast seems to be cooking too fast, turn the heat down to medium. You want a steady sizzle, not a raging sear.)\r\nTurn the brisket over and cook for a few minutes more to brown the other side.\r\n\r\n3 Sauté the onions and garlic: When the brisket has browned, remove it from the pot and set aside. There should be a couple tablespoons of fat rendered in the pot, if not, add some olive oil.\r\nAdd the chopped onions and increase the heat to high. Sprinkle a little salt on the onions. Sauté, stirring often, until the onions are lightly browned, 5-8 minutes. Stir in the garlic and cook 1-2 more minutes.\r\n \r\n4 Return brisket to pot, add herbs, stock, bring to simmer, cover, cook in oven: Preheat the oven to 300°F. Use kitchen twine to tie together the bay leaves, rosemary and thyme.\r\nMove the onions and garlic to the sides of the pot and nestle the brisket inside. Add the beef stock and the tied-up herbs. Bring the stock to a boil on the stovetop.\r\nCover the pot, place the pot in the 300°F oven and cook for 3 hours. Carefully flip the brisket every hour so it cooks evenly.\r\n \r\n5 Add carrots, continue to cook: After 3 hours, add the carrots. Cover the pot and cook for 1 hour more, or until the carrots are cooked through and the brisket is falling-apart tender.\r\n6 Remove brisket to cutting board, tent with foil: When the brisket is falling-apart tender, take the pot out of the oven and remove the brisket to a cutting board. Cover it with foil. Pull out and discard the herbs.\r\n7 Make sauce (optional): At this point you have two options. You can serve as is, or you can make a sauce with the drippings and some of the onions. If you serve as is, skip this step.\r\nTo make a sauce, remove the carrots and half of the onions, set aside and cover them with foil. Pour the ingredients that are remaining into the pot into a blender, and purée until smooth. If you want, add 1 tablespoon of mustard to the mix. Put into a small pot and keep warm.\r\n8 Slice the meat across the grain: Notice the lines of the muscle fibers of the roast. This is the "grain" of the meat. Slice the meat perpendicular to these lines, or across the grain (cutting this way further tenderizes the meat), in 1/4-inch to 1/2-inch slices.\r\nServe with the onions, carrots and gravy. Serve with mashed, roasted or boiled potatoes, egg noodles or polenta.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg',
    strTags: 'Meat',
    strYoutube: 'https://www.youtube.com/watch?v=gh48wM6bPWQ',
    strIngredient1: 'Beef Brisket',
    strIngredient2: 'Salt',
    strIngredient3: 'Onion',
    strIngredient4: 'Garlic',
    strIngredient5: 'Thyme',
    strIngredient6: 'Rosemary',
    strIngredient7: 'Bay Leaves',
    strIngredient8: 'beef stock',
    strIngredient9: 'Carrots',
    strIngredient10: 'Mustard',
    strIngredient11: 'Potatoes',
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '4-5 pound',
    strMeasure2: 'Dash',
    strMeasure3: '3',
    strMeasure4: '5 cloves',
    strMeasure5: '1 Sprig',
    strMeasure6: '1 sprig ',
    strMeasure7: '4',
    strMeasure8: '2 cups',
    strMeasure9: '3 Large',
    strMeasure10: '1 Tbsp',
    strMeasure11: '4 Mashed',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'http://www.simplyrecipes.com/recipes/beef_brisket_pot_roast/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52812.png',
    idCategory: '1',
    idIngredients: [
      '23',
      '281',
      '364',
      '149',
      '313',
      '396',
      '21',
      '26',
      '49',
      '219',
      '253',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53070',
    strMeal: 'Beef Caldereta',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Filipino',
    strInstructions:
      '0.\tHeat oil in a cooking pot. Saute onion and garlic until onion softens\r\n1.\tAdd beef. Saute until the outer part turns light brown.\r\n2.\tAdd soy sauce. Pour tomato sauce and water. Let boil.\r\n3.\tAdd Knorr Beef Cube. Cover the pressure cooker. Cook for 30 minutes.\r\n4.\tPan-fry carrot and potato until it browns. Set aside.\r\n5.\tAdd chili pepper, liver spread and peanut butter. Stir.\r\n6.\tAdd bell peppers, fried potato and carrot. Cover the pot. Continue cooking for 5 to 7 minutes.\r\n7.\tSeason with salt and ground black pepper. Serve.\r\n',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=yI7hTz0ft5k',
    strIngredient1: 'Beef',
    strIngredient2: 'Beef Stock',
    strIngredient3: 'Soy Sauce',
    strIngredient4: 'Water',
    strIngredient5: 'Green Pepper',
    strIngredient6: 'Red Pepper',
    strIngredient7: 'Potatoes',
    strIngredient8: 'Carrots',
    strIngredient9: 'Tomato Puree',
    strIngredient10: 'Peanut Butter',
    strIngredient11: 'Chilli Powder',
    strIngredient12: 'Onion',
    strIngredient13: 'Garlic',
    strIngredient14: 'Olive Oil',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2kg cut cubes',
    strMeasure2: '1',
    strMeasure3: '1 tbs',
    strMeasure4: '2 cups ',
    strMeasure5: '1 sliced',
    strMeasure6: '1 sliced',
    strMeasure7: '1 sliced',
    strMeasure8: '1 sliced',
    strMeasure9: '8 ounces',
    strMeasure10: '3  tablespoons',
    strMeasure11: '5',
    strMeasure12: '1 chopped',
    strMeasure13: '5 cloves',
    strMeasure14: '3 tbs',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.kawalingpinoy.com/beef-caldereta/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53070.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '26',
      '296',
      '333',
      '425',
      '264',
      '253',
      '49',
      '316',
      '238',
      '75',
      '364',
      '149',
      '224',
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53053',
    strMeal: 'Beef Rendang',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Malaysian',
    strInstructions:
      'Chop the spice paste ingredients and then blend it in a food processor until fine.\r\nHeat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat.\r\nLower the heat to low, cover the lid, and simmer for 1 to 1 1/2 hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=Ot-dmfBaZrA',
    strIngredient1: 'Beef',
    strIngredient2: 'Vegetable Oil',
    strIngredient3: 'Cinnamon Stick',
    strIngredient4: 'Cloves',
    strIngredient5: 'Star Anise',
    strIngredient6: 'Cardamom',
    strIngredient7: 'Coconut Cream',
    strIngredient8: 'Water',
    strIngredient9: 'Tamarind Paste',
    strIngredient10: 'Lime',
    strIngredient11: 'Sugar',
    strIngredient12: 'Challots',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1lb',
    strMeasure2: '5 tbs',
    strMeasure3: '1',
    strMeasure4: '3',
    strMeasure5: '3',
    strMeasure6: '3',
    strMeasure7: '1 cup ',
    strMeasure8: '1 cup ',
    strMeasure9: '2 tbs',
    strMeasure10: '6',
    strMeasure11: '1 tbs',
    strMeasure12: '5',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://rasamalaysia.com/beef-rendang-recipe-rendang-daging/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53053.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '327',
      '85',
      '87',
      '497',
      '47',
      '90',
      '333',
      '309',
      '202',
      '305',
      '57',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53039',
    strMeal: 'Piri-piri chicken and slaw',
    strDrinkAlternate: null,
    strCategory: 'Chicken',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nWhizz together all of the marinade ingredients in a small food processor. Rub the marinade onto the chicken and leave for 1 hour at room temperature.\r\n\r\nSTEP 2\r\n\r\nHeat the oven to 190C/fan 170C/gas 5. Put the chicken in a roasting tray and cook for 1 hour 20 minutes. Rest under loose foil for 20 minutes. While the chicken is resting, mix together the slaw ingredients and season. Serve the chicken with slaw, fries and condiments.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=_RKwKjskopk',
    strIngredient1: 'Chicken',
    strIngredient2: 'Red Chilli',
    strIngredient3: 'Garlic',
    strIngredient4: 'Ginger',
    strIngredient5: 'Dried Oregano',
    strIngredient6: 'Coriander',
    strIngredient7: 'Paprika',
    strIngredient8: 'Red Wine Vinegar',
    strIngredient9: 'Oil',
    strIngredient10: 'Red Onions',
    strIngredient11: 'Carrots',
    strIngredient12: 'Beetroot',
    strIngredient13: 'Cabbage',
    strIngredient14: 'Mayonnaise',
    strIngredient15: 'Greek Yogurt',
    strIngredient16: 'Red Wine Vinegar',
    strIngredient17: 'Cumin Seeds',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1.5kg',
    strMeasure2: '3 chopped',
    strMeasure3: '2 cloves',
    strMeasure4: '1 tsp ',
    strMeasure5: '1 tsp ',
    strMeasure6: '1 tsp ',
    strMeasure7: '1 tsp ',
    strMeasure8: '2 tbs',
    strMeasure9: '2 tbs',
    strMeasure10: '1 sliced',
    strMeasure11: '2',
    strMeasure12: '1',
    strMeasure13: '4 leaves',
    strMeasure14: '2 tbs',
    strMeasure15: '2 tbs',
    strMeasure16: '2 tbs',
    strMeasure17: '1 tsp ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/family/piri-piri-chicken-and-winter-slaw/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53039.png',
    idCategory: '2',
    idIngredients: [
      '1',
      '259',
      '149',
      '154',
      '116',
      '95',
      '232',
      '394',
      '223',
      '263',
      '49',
      '604',
      '440',
      '576',
      '162',
      '394',
      '105',
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52775',
    strMeal: 'Vegan Lasagna',
    strDrinkAlternate: null,
    strCategory: 'Vegan',
    strArea: 'Italian',
    strInstructions:
      '1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg',
    strTags: 'Vegan,Pasta',
    strYoutube: 'https://www.youtube.com/watch?v=VU8cXvlGbvc',
    strIngredient1: 'green red lentils',
    strIngredient2: 'carrot',
    strIngredient3: 'onion',
    strIngredient4: 'zucchini',
    strIngredient5: 'coriander',
    strIngredient6: 'spinach',
    strIngredient7: 'lasagne sheets',
    strIngredient8: 'vegan butter',
    strIngredient9: 'flour',
    strIngredient10: 'soya milk',
    strIngredient11: 'mustard',
    strIngredient12: 'vinegar',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '1 cups',
    strMeasure2: '1',
    strMeasure3: '1',
    strMeasure4: '1 small',
    strMeasure5: 'sprinking',
    strMeasure6: '150g',
    strMeasure7: '10',
    strMeasure8: '35g',
    strMeasure9: '4 tablespoons',
    strMeasure10: '300ml',
    strMeasure11: '1.5 teaspoons',
    strMeasure12: '1 teaspoon',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52775.png',
    idCategory: '11',
    idIngredients: [
      '167',
      null,
      '364',
      '344',
      '95',
      '299',
      '194',
      '326',
      '137',
      '297',
      '219',
      '332',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52803',
    strMeal: 'Beef Wellington',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'British',
    strInstructions:
      "Put the mushrooms into a food processor with some seasoning and pulse to a rough paste. Scrape the paste into a pan and cook over a high heat for about 10 mins, tossing frequently, to cook out the moisture from the mushrooms. Spread out on a plate to cool.\r\nHeat in a frying pan and add a little olive oil. Season the beef and sear in the hot pan for 30 secs only on each side. (You don't want to cook it at this stage, just colour it). Remove the beef from the pan and leave to cool, then brush all over with the mustard.\r\nLay a sheet of cling film on a work surface and arrange the Parma ham slices on it, in slightly overlapping rows. With a palette knife, spread the mushroom paste over the ham, then place the seared beef fillet in the middle. Keeping a tight hold of the cling film from the edge, neatly roll the Parma ham and mushrooms around the beef to form a tight barrel shape. Twist the ends of the cling film to secure. Chill for 15-20 mins to allow the beef to set and keep its shape.\r\nRoll out the puff pastry on a floured surface to a large rectangle, the thickness of a £1 coin. Remove the cling film from the beef, then lay in the centre. Brush the surrounding pastry with egg yolk. Fold the ends over, the wrap the pastry around the beef, cutting off any excess. Turn over, so the seam is underneath, and place on a baking sheet. Brush over all the pastry with egg and chill for about 15 mins to let the pastry rest.\r\nHeat the oven to 200C, 400F, gas 6.\r\nLightly score the pastry at 1cm intervals and glaze again with beaten egg yolk. Bake for 20 minutes, then lower the oven setting to 180C, 350F, gas 4 and cook for another 15 mins. Allow to rest for 10-15 mins before slicing and serving with the side dishes of your choice. The beef should still be pink in the centre when you serve it.",
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg',
    strTags: 'Meat,Stew',
    strYoutube: 'https://www.youtube.com/watch?v=FS8u1RBdf6I',
    strIngredient1: 'mushrooms',
    strIngredient2: 'English Mustard',
    strIngredient3: 'Olive Oil',
    strIngredient4: 'Beef Fillet',
    strIngredient5: 'Parma ham',
    strIngredient6: 'Puff Pastry',
    strIngredient7: 'Flour',
    strIngredient8: 'Egg Yolks',
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '400g',
    strMeasure2: '1-2tbsp',
    strMeasure3: 'Dash',
    strMeasure4: '750g piece',
    strMeasure5: '6-8 slices',
    strMeasure6: '500g',
    strMeasure7: 'Dusting',
    strMeasure8: '2 Beaten ',
    strMeasure9: '',
    strMeasure10: '',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52803.png',
    idCategory: '1',
    idIngredients: [
      '218',
      '125',
      '224',
      '24',
      '233',
      '255',
      '137',
      '122',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52979',
    strMeal: 'Bitterballen (Dutch meatballs)',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Dutch',
    strInstructions:
      'Melt the butter in a skillet or pan. When melted, add the flour little by little and stir into a thick paste. Slowly stir in the stock, making sure the roux absorbs the liquid. Simmer for a couple of minutes on a low heat while you stir in the onion, parsley and the shredded meat. The mixture should thicken and turn into a heavy, thick sauce.\r\n\r\nPour the mixture into a shallow container, cover and refrigerate for several hours, or until the sauce has solidified.\r\n\r\nTake a heaping tablespoon of the cold, thick sauce and quickly roll it into a small ball. Roll lightly through the flour, then the egg and finally the breadcrumbs. Make sure that the egg covers the whole surface of the bitterbal. When done, refrigerate the snacks while the oil in your fryer heats up to 190C (375F). Fry four bitterballen at a time, until golden.\r\n\r\nServe on a plate with a nice grainy or spicy mustard. \r\n',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg',
    strTags: 'DinnerParty,HangoverFood,Alcoholic',
    strYoutube: 'https://www.youtube.com/watch?v=q8AKfYUtDuM',
    strIngredient1: 'Butter',
    strIngredient2: 'Flour',
    strIngredient3: 'Beef Stock',
    strIngredient4: 'Onion',
    strIngredient5: 'Parsley',
    strIngredient6: 'Beef',
    strIngredient7: 'Salt',
    strIngredient8: 'Pepper',
    strIngredient9: 'Nutmeg',
    strIngredient10: 'Flour',
    strIngredient11: 'Eggs',
    strIngredient12: 'Breadcrumbs',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '100g ',
    strMeasure2: '150g',
    strMeasure3: '700ml',
    strMeasure4: '30g',
    strMeasure5: '1 tbs',
    strMeasure6: '400g',
    strMeasure7: 'Pinch',
    strMeasure8: 'Pinch',
    strMeasure9: 'Pinch',
    strMeasure10: '50g',
    strMeasure11: '2 Beaten ',
    strMeasure12: '50g',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.holland.com/global/tourism/information/traditional-dutch-food/bitterballen.htm',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52979.png',
    idCategory: '1',
    idIngredients: [
      '41',
      '137',
      '26',
      '364',
      '237',
      '3',
      '281',
      '244',
      '222',
      '137',
      '123',
      '36',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53063',
    strMeal: 'Chivito uruguayo',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Unknown',
    strInstructions:
      'Crush the meat so that it is finite and we put it on a griddle to brown. Put the eggs, bacon and ham to fry.\r\nCut the bread in half, put the beef brisket, the fried eggs, the bacon, the ham, the mozzarella, the tomato and the lettuce. Cover with the other half of the bread and serve.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg',
    strTags: null,
    strYoutube:
      'https://www.youtube.com/watch?v=0PXbbL1QdaA&ab_channel=D%C3%ADadeCocina',
    strIngredient1: 'Beef Brisket',
    strIngredient2: 'Bread',
    strIngredient3: 'Lettuce',
    strIngredient4: 'Tomato',
    strIngredient5: 'Ham',
    strIngredient6: 'Mozzarella',
    strIngredient7: 'Bacon',
    strIngredient8: 'Egg',
    strIngredient9: 'Onion',
    strIngredient10: 'Pepper',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2',
    strMeasure2: '2',
    strMeasure3: '1',
    strMeasure4: '1',
    strMeasure5: '100g ',
    strMeasure6: '100g ',
    strMeasure7: '100g ',
    strMeasure8: '1',
    strMeasure9: '1',
    strMeasure10: '1',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://cookpad.com/uy/recetas/116102-chivito-uruguayo',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53063.png',
    idCategory: '1',
    idIngredients: [
      '23',
      '35',
      '201',
      '365',
      '448',
      '402',
      '14',
      '483',
      '364',
      '244',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52998',
    strMeal: 'Corned Beef and Cabbage',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Irish',
    strInstructions:
      '1\r\n\r\nPlace corned beef in large pot or Dutch oven and cover with water. Add the spice packet that came with the corned beef. Cover pot and bring to a boil, then reduce to a simmer. Simmer approximately 50 minutes per pound or until tender.\r\n\r\n2\r\n\r\nAdd whole potatoes and peeled and cut carrots, and cook until the vegetables are almost tender. Add cabbage and cook for 15 more minutes. Remove meat and let rest 15 minutes.\r\n\r\n3\r\n\r\nPlace vegetables in a bowl and cover. Add as much broth (cooking liquid reserved in the Dutch oven or large pot) as you want. Slice meat across the grain.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xb97a81583266727.jpg',
    strTags: '',
    strYoutube: '',
    strIngredient1: 'Beef Brisket',
    strIngredient2: 'Small Potatoes',
    strIngredient3: 'Carrots',
    strIngredient4: 'Cabbage',
    strIngredient5: '',
    strIngredient6: '',
    strIngredient7: '',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '3 Lbs',
    strMeasure2: '10',
    strMeasure3: '5',
    strMeasure4: '1 head',
    strMeasure5: ' ',
    strMeasure6: ' ',
    strMeasure7: ' ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: '',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52998.png',
    idCategory: '1',
    idIngredients: [
      '23',
      '292',
      '49',
      '440',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53058',
    strMeal: 'Croatian Bean Stew',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Croatian',
    strInstructions:
      'Heat the oil in a pan. Add the chopped vegetables and sauté until tender. Take a pot, empty the beans together with the vegetables into it, put the sausages inside and cook for further 20 minutes on a low heat. Or, put it in an oven and bake it at a temperature of 180ºC/350ºF for 30 minutes. This dish is even better reheated the next day.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg',
    strTags: 'Warming, Soup, Beans',
    strYoutube: 'https://www.youtube.com/watch?v=mrjnQal3S1A',
    strIngredient1: 'Cannellini Beans',
    strIngredient2: 'Vegetable Oil',
    strIngredient3: 'Tomatoes',
    strIngredient4: 'Challots',
    strIngredient5: 'Garlic',
    strIngredient6: 'Parsley',
    strIngredient7: 'Chorizo',
    strIngredient8: '',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 cans',
    strMeasure2: '3 tbs',
    strMeasure3: '2 cups ',
    strMeasure4: '5',
    strMeasure5: '2 cloves',
    strMeasure6: 'Pinch',
    strMeasure7: '1/2 kg chopped ',
    strMeasure8: ' ',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53058.png',
    idCategory: '1',
    idIngredients: [
      '46',
      '327',
      '317',
      '57',
      '149',
      '237',
      '81',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52826',
    strMeal: 'Braised Beef Chilli',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Mexican',
    strInstructions:
      'Preheat the oven to 120C/225F/gas mark 1.\r\n\r\nTake the meat out of the fridge to de-chill. Pulse the onions and garlic in a food processor until finely chopped. Heat 2 tbsp olive oil in a large casserole and sear the meat on all sides until golden.\r\n\r\nSet to one side and add another small slug of oil to brown the chorizo. Remove and add the onion and garlic, spices, herbs and chillies then cook until soft in the chorizo oil. Season with salt and pepper and add the vinegar, tomatoes, ketchup and sugar.\r\n\r\nPut all the meat back into the pot with 400ml water (or red wine if you prefer), bring up to a simmer and cook, covered, in the low oven.\r\n\r\nAfter 2 hours, check the meat and add the beans. Cook for a further hour and just before serving, pull the meat apart with a pair of forks.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=z4kSoJgsu6Y',
    strIngredient1: 'Beef',
    strIngredient2: 'Onions',
    strIngredient3: 'Garlic',
    strIngredient4: 'Olive oil',
    strIngredient5: 'Chorizo',
    strIngredient6: 'Cumin',
    strIngredient7: 'All spice',
    strIngredient8: 'Cloves',
    strIngredient9: 'Cinnamon stick',
    strIngredient10: 'Bay Leaves',
    strIngredient11: 'Oregano',
    strIngredient12: 'Ancho Chillies',
    strIngredient13: 'Balsamic Vinegar',
    strIngredient14: 'Plum Tomatoes',
    strIngredient15: 'Tomato Ketchup',
    strIngredient16: 'Dark Brown Sugar',
    strIngredient17: 'Borlotti Beans',
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '1kg',
    strMeasure2: '3',
    strMeasure3: '4 cloves',
    strMeasure4: 'Dash',
    strMeasure5: '300g',
    strMeasure6: '2 tsp',
    strMeasure7: '2 tsp',
    strMeasure8: '1 tsp',
    strMeasure9: '1 large',
    strMeasure10: '3',
    strMeasure11: '2 tsp dried',
    strMeasure12: '2 ancho',
    strMeasure13: '3 tbsp',
    strMeasure14: '2 x 400g',
    strMeasure15: '2 tbsp',
    strMeasure16: '2 tbsp',
    strMeasure17: '2 x 400g tins',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'http://www.telegraph.co.uk/food-and-drink/recipes/braised-beef-chilli-con-carne/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52826.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '227',
      '149',
      '224',
      '81',
      '104',
      null,
      '87',
      '85',
      '21',
      '230',
      '545',
      '16',
      '249',
      '315',
      '107',
      '31',
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53056',
    strMeal: 'Croatian lamb peka',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Croatian',
    strInstructions:
      'Preheat oven to 200°C fan / 220°C / 425°F / Gas mark 7\r\nIf you have not bought diced lamb, cut your lamb shoulder or leg into large chunks and place to one side.\r\nChunks of chopped lamb of a red chopping board\r\nMake oil marinade -\r\nMix 80ml of olive oil in a bowl with garlic puree, sundried tomato puree ,black pepper and salt.\r\nolive oil, gia sundried tomato puree and gia garlic puree and black pepper mixed together in a silver bowl to make Croatian peka\r\nAdd potatoes and vegetables into a large lidded casserole dish.\r\nChopped up vegetables which consist of chopped up red onion, courgette, potatoes red peppers in a cast iron pan\r\nPlace diced lamb on top of the vegetables, pour the marinade and wine over the top.\r\nChunks of lamb covered in in a sundried tomato oil sauce which is on top of chopped red onion, aubergine, courgette and potatoes in a cast iron pan\r\nAdd the rosemary, thyme and sage, trying to keep the herbs on top.\r\nSo you can easily remove the herb stalks once cooked.\r\nChunks of lamb coated in a sundried tomato oil sauce and covered with thyme, rosemary and sage which is on top of chopped red onion, aubergine, courgette and potatoes in a cast iron pan\r\nPlace lid on the casserole dish and cook for 1hr 30 minute\r\nIf you do not have a lid cover very well with kitchen foil\r\nCast iron dish with lid on in the oven\r\nTake the lid off, remove any thick herb stems. Stir in 2 tbsp of olive oil.\r\nCook for a further 20-30 mins.\r\nCooked Croatian Lamb Peka in a cast iron pan in the oven\r\nServe with fresh homemade bread to dip into the juices.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/pn59o51628769837.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=K0ipnz4fwJI',
    strIngredient1: 'Potatoes',
    strIngredient2: 'Courgettes',
    strIngredient3: 'Carrots',
    strIngredient4: 'Green Pepper',
    strIngredient5: 'Aubergine',
    strIngredient6: 'Onion',
    strIngredient7: 'Lamb Shoulder',
    strIngredient8: 'Garlic Sauce',
    strIngredient9: 'Tomato Puree',
    strIngredient10: 'Olive Oil',
    strIngredient11: 'Thyme',
    strIngredient12: 'White Wine',
    strIngredient13: 'Pepper',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '600g',
    strMeasure2: '1 chopped',
    strMeasure3: '1 chopped',
    strMeasure4: '1 chopped',
    strMeasure5: '1 small',
    strMeasure6: '1 Large Chopped',
    strMeasure7: '800g',
    strMeasure8: '1 tbs',
    strMeasure9: '1 tbs',
    strMeasure10: '80 ml ',
    strMeasure11: 'Sprinking',
    strMeasure12: '250ml',
    strMeasure13: 'Pinch',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://flawlessfood.co.uk/croatian-lamb-peka/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53056.png',
    idCategory: '1',
    idIngredients: [
      '253',
      '426',
      '49',
      '425',
      '11',
      '364',
      '381',
      '152',
      '316',
      '224',
      '313',
      '338',
      '244',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52781',
    strMeal: 'Irish stew',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Irish',
    strInstructions:
      "Heat the oven to 180C/350F/gas mark 4. Drain and rinse the soaked wheat, put it in a medium pan with lots of water, bring to a boil and simmer for an hour, until cooked. Drain and set aside.\r\n\r\nSeason the lamb with a teaspoon of salt and some black pepper. Put one tablespoon of oil in a large, deep sauté pan for which you have a lid; place on a medium-high heat. Add some of the lamb – don't overcrowd the pan – and sear for four minutes on all sides. Transfer to a bowl, and repeat with the remaining lamb, adding oil as needed.\r\n\r\nLower the heat to medium and add a tablespoon of oil to the pan. Add the shallots and fry for four minutes, until caramelised. Tip these into the lamb bowl, and repeat with the remaining vegetables until they are all nice and brown, adding more oil as you need it.\r\n\r\nOnce all the vegetables are seared and removed from the pan, add the wine along with the sugar, herbs, a teaspoon of salt and a good grind of black pepper. Boil on a high heat for about three minutes.\r\n\r\nTip the lamb, vegetables and whole wheat back into the pot, and add the stock. Cover and boil for five minutes, then transfer to the oven for an hour and a half.\r\n\r\nRemove the stew from the oven and check the liquid; if there is a lot, remove the lid and boil for a few minutes.",
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg',
    strTags: 'Stew,Meat',
    strYoutube: 'https://www.youtube.com/watch?v=kYH2qJXnSMo',
    strIngredient1: 'whole wheat',
    strIngredient2: 'lamb loin chops',
    strIngredient3: 'olive oil',
    strIngredient4: 'shallots',
    strIngredient5: 'carrots',
    strIngredient6: 'turnips',
    strIngredient7: 'celeriac',
    strIngredient8: 'charlotte potatoes',
    strIngredient9: 'white wine',
    strIngredient10: 'caster sugar',
    strIngredient11: 'fresh thyme',
    strIngredient12: 'oregano',
    strIngredient13: 'chicken stock',
    strIngredient14: null,
    strIngredient15: null,
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: '300g soaked overnight in water',
    strMeasure2: '2kg cut into 3cm cubes',
    strMeasure3: '120ml',
    strMeasure4: '24 Skinned',
    strMeasure5: '4 large',
    strMeasure6: '2',
    strMeasure7: '1',
    strMeasure8: '350g',
    strMeasure9: '150ml',
    strMeasure10: '1 tsp',
    strMeasure11: '4 sprigs',
    strMeasure12: '4 sprigs',
    strMeasure13: '450ml',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: 'http://www.ottolenghi.co.uk/recipes/meat/irish-stew-shop',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52781.png',
    idCategory: '1',
    idIngredients: [
      '340',
      '192',
      '224',
      '289',
      '49',
      '322',
      '54',
      '58',
      '338',
      '52',
      '144',
      '230',
      '68',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52938',
    strMeal: 'Jamaican Beef Patties',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Jamaican',
    strInstructions:
      'Make the Pastry Dough\r\n\r\nTo a large bowl, add flour, 1 teaspoon salt, and turmeric and mix thoroughly.\r\nRub shortening into flour until there are small pieces of shortening completely covered with flour.\r\nPour in 1/2 cup of the ice water and mix with your hands to bring the dough together. Keep adding ice water 2 to 3 tablespoons at a time until the mixture forms a dough.\r\nAt this stage, you can cut the dough into 2 large pieces, wrap in plastic and refrigerate for 30 minutes before using it.\r\nAlternatively, cut the dough into 10 to 12 equal pieces, place on a platter or baking sheet, cover securely with plastic wrap and let chill for 30 minutes while you make the filling.\r\nMake the Filling\r\n\r\nAdd ground beef to a large bowl. Sprinkle in allspice and black pepper. Mix together and set aside.\r\nHeat oil in a skillet until hot.\r\nAdd onions and sauté until translucent. Add hot pepper, garlic and thyme and continue to sauté for another minute. Add 1/4 teaspoon salt.\r\nAdd seasoned ground beef and toss to mix, breaking up any clumps, and let cook until the meat is no longer pink.\r\nAdd ketchup and more salt to taste.\r\nPour in 2 cups of water and stir. Bring the mixture to a boil then reduce heat and let simmer until most of the liquid has evaporated and whatever is remaining has reduced to a thick sauce.\r\nFold in green onions. Remove from heat and let cool completely.\r\nAssemble the Patties\r\n\r\nBeat the egg and water together to make an egg wash. Set aside.\r\nNow you can prepare the dough in two ways.\r\nFirst Method: Flour the work surface and rolling pin. If you had cut it into 2 large pieces, then take one of the large pieces and roll it out into a very large circle. Take a bowl with a wide rim (about 5 inches) and cut out three circles.\r\n\r\nPlace about 3 heaping tablespoons of the filling onto 1/2 of each circle. Dip a finger into the water and moisten the edges of the pastry. Fold over the other half and press to seal. \r\n\r\nTake a fork and crimp the edges. Cut off any extra to make it look neat and uniform. Place on a parchment-lined baking sheet and continue to work until you have rolled all the dough and filled the patties.\r\nSecond Method: If you had pre-cut the dough into individual pieces, work with one piece of dough at a time. Roll it out on a floured surface into a 5-inch circle or a little larger. Don’t worry if the edges are not perfect.\r\n\r\nPlace 3 heaping tablespoons of the filling on one side of the circle. Dip a finger into the water and moisten the edges of the pastry. Fold over the other half and press to seal.\r\n\r\nTake a fork and crimp the edges. Cut off any extra to make it look neat and uniform. Place on a parchment-lined baking sheet and continue work until you have rolled all the dough and filled the patties.\r\n\r\nFrying and Serving the Patties\r\n\r\nAfter forming the patties, place the pans in the refrigerator while you heat the oven to 350 F.\r\nJust before adding the pans with the patties to the oven, brush the patties with egg wash.\r\nBake patties for 30 minutes or until golden brown.\r\nCool on wire racks.\r\nServe warm.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wsqqsw1515364068.jpg',
    strTags: 'Snack,Spicy',
    strYoutube: 'https://www.youtube.com/watch?v=ypQjoiZiTac',
    strIngredient1: 'Plain Flour',
    strIngredient2: 'Salt',
    strIngredient3: 'Curry Powder',
    strIngredient4: 'Butter',
    strIngredient5: 'Water',
    strIngredient6: 'Minced Beef',
    strIngredient7: 'Allspice',
    strIngredient8: 'Black Pepper',
    strIngredient9: 'Vegetable Oil',
    strIngredient10: 'Onions',
    strIngredient11: 'Red Pepper',
    strIngredient12: 'Garlic',
    strIngredient13: 'Thyme',
    strIngredient14: 'Salt',
    strIngredient15: 'Tomato Ketchup',
    strIngredient16: 'Water',
    strIngredient17: 'Onions',
    strIngredient18: 'Egg',
    strIngredient19: 'Water',
    strIngredient20: 'Water',
    strMeasure1: '4 cups ',
    strMeasure2: '1 tsp ',
    strMeasure3: '1 tsp ',
    strMeasure4: '250g',
    strMeasure5: '1 cup ',
    strMeasure6: '900g',
    strMeasure7: '1 tsp ',
    strMeasure8: '1/2 tsp',
    strMeasure9: '2 tbs',
    strMeasure10: '1 cup ',
    strMeasure11: 'Ground',
    strMeasure12: '2 tsp ground',
    strMeasure13: '1 tbs',
    strMeasure14: '1/4 tsp',
    strMeasure15: '2 tbs',
    strMeasure16: '2 cups ',
    strMeasure17: '1/2 cup ',
    strMeasure18: '1 beaten',
    strMeasure19: '1 tbs',
    strMeasure20: '1/4 cup',
    strSource: 'https://www.thespruce.com/jamaican-beef-patties-recipe-2137762',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52938.png',
    idCategory: '1',
    idIngredients: [
      '248',
      '281',
      '106',
      '41',
      '333',
      '387',
      '548',
      '29',
      '327',
      '227',
      '264',
      '149',
      '313',
      '281',
      '315',
      '333',
      '227',
      '483',
      '333',
      '333',
    ],
  },
  {
    idMeal: '52876',
    strMeal: 'Minced Beef Pie',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'British',
    strInstructions:
      'Preheat the oven to 200C/400F/Gas 6.\r\nHeat the oil in a deep frying pan and fry the beef mince for 4-5 minutes, breaking it up with a wooden spoon as it browns.\r\nAdd the onion and cook for 2-3 minutes, then stir in the tomato purée and cook for 2-3 more minutes. Stir in the flour and cook for a further minute, then add the chopped mushrooms, the stout or beef stock and a couple of dashes of Worcestershire sauce. Bring to the boil, then reduce the heat, cover the pan with a lid and leave to simmer for 20 minutes. Set aside and leave to cool, then turn the meat mixture into a one litre pie dish.\r\nRoll out the pastry on a floured work surface until it is slightly larger than the pie dish. Gently drape the pastry over the dish, pressing firmly onto the edges. Trim, then shape the edges into a fluted shape.\r\nCut some leaf shapes out of the pastry trimmings and decorate the top of the pie, sticking them to the pastry with the beaten egg yolk.\r\nMake three or four slits in the pastry to allow the steam to escape, then brush the pie with the rest of the beaten egg yolk and bake in the oven for 20-25 minutes, or until golden-brown.\r\nTo serve, slice into wedges.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg',
    strTags: 'Pie,Meat',
    strYoutube: 'https://www.youtube.com/watch?v=QY47h-uqq5g',
    strIngredient1: 'Vegetable Oil',
    strIngredient2: 'Minced Beef',
    strIngredient3: 'Onion',
    strIngredient4: 'Tomato Puree',
    strIngredient5: 'Plain Flour',
    strIngredient6: 'Mushrooms',
    strIngredient7: 'Beef Stock',
    strIngredient8: 'Worcestershire Sauce',
    strIngredient9: 'Shortcrust Pastry',
    strIngredient10: 'Egg Yolks',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '2 tbs',
    strMeasure2: '500g',
    strMeasure3: '1 chopped',
    strMeasure4: '1 tbls',
    strMeasure5: '1 ½ tbsp',
    strMeasure6: '75g',
    strMeasure7: '250ml',
    strMeasure8: 'Dash',
    strMeasure9: '400g',
    strMeasure10: '1',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'https://www.bbc.co.uk/food/recipes/mincedbeefpie_89198',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52876.png',
    idCategory: '1',
    idIngredients: [
      '327',
      '387',
      '364',
      '316',
      '248',
      '218',
      '26',
      '342',
      '419',
      '122',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53006',
    strMeal: 'Moussaka',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Greek',
    strInstructions:
      'Heat the grill to high. Brown the beef in a deep ovenproof frying pan over a high heat for 5 mins. Meanwhile, prick the aubergine with a fork, then microwave on High for 3-5 mins until soft. Mix the yogurt, egg and parmesan together, then add a little seasoning.\r\n\r\nStir the tomatoes, purée and potatoes in with the beef with some seasoning and heat through. Smooth the surface of the beef mixture with the back of a spoon, then slice the cooked aubergine and arrange on top. Pour the yogurt mixture over the aubergines, smooth out evenly, then grill until the topping has set and turned golden.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=8U_29i9Qp5U',
    strIngredient1: 'Beef',
    strIngredient2: 'Aubergine',
    strIngredient3: 'Greek Yogurt',
    strIngredient4: 'Egg',
    strIngredient5: 'Parmesan',
    strIngredient6: 'Tomato',
    strIngredient7: 'Tomato Puree',
    strIngredient8: 'Potatoes',
    strIngredient9: '',
    strIngredient10: '',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '500g',
    strMeasure2: '1 large',
    strMeasure3: '150g',
    strMeasure4: '1 beaten',
    strMeasure5: '3 tbs',
    strMeasure6: '400g',
    strMeasure7: '4 tbs',
    strMeasure8: '350g',
    strMeasure9: ' ',
    strMeasure10: ' ',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource: 'https://www.bbcgoodfood.com/recipes/must-make-moussaka',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53006.png',
    idCategory: '1',
    idIngredients: [
      '3',
      '11',
      '162',
      '483',
      '234',
      '365',
      '316',
      '253',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52805',
    strMeal: 'Lamb Biryani',
    strDrinkAlternate: null,
    strCategory: 'Lamb',
    strArea: 'Indian',
    strInstructions:
      'Grind the cashew, poppy seeds and cumin seeds into a smooth paste, using as little water as possible. Set aside. \r\n\r\nDeep fry the sliced onions when it is hot. Don’t overcrowd the oil. When the onions turn light brown, remove from oil and drain on paper towel. The fried onion will crisp up as it drains. Also fry the cashewnuts till golden brown. Set aside.\r\n\r\nWash the rice and soak in water for twenty minutes.\r\nMeanwhile, take a big wide pan, add oil in medium heat, add the sliced onions, add the blended paste, to it add the green chillies, ginger garlic paste and garlic and fry for a minute.\r\nThen add the tomatoes and sauté them well till they are cooked and not mushy.\r\n\r\nThen to it add the red chilli powder, biryani powder, mint, coriander leaves and sauté them well.\r\nAdd the yogurt and mix well. I always move the skillet away from the heat when adding yogurt which prevents it from curdling.\r\n\r\nNow after returning the skillet back to the stove, add the washed lamb and salt and ½ cup water and mix well. Cook for 1 hour and cook it covered in medium low heat or put it in a pressure cooker for 6 whistles. If the water is not drained totally, heat it by keeping it open.\r\n\r\nTake another big pan, add thrice the cup of rice you use, and boil it. When it is boiling high, add the rice, salt and jeera and mix well. After 7 minutes exact or when the rice is 80% done. Switch off and drain the rice.\r\n\r\nNow, the layering starts. To the lamb, pat and level it. Add the drained hot rice on the top of it. Garnish with fried onions, ghee, mint, coriander leaves and saffron dissolved in milk.\r\n\r\nCover the dish and bake in a 350f oven for 15 minutes or till the cooked but not mushy. Or cook in the stove medium heat for 12 minutes and lowest heat for 5 minutes. And switch off. Mix and serve hot!\r\nNotes\r\n1. If you are cooking in oven, do make sure to cook in a big oven safe pan and cover it tight and then keep in oven for the final step.\r\n2. You can skip biryani masala if you don’t have and add just garam masala (1 tsp and red chilli powder – 3 tsp instead of 1 tsp)\r\n3. If it is spicy in the end, squeeze some lemon, it will reduce the heat and enhance the flavors also.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg',
    strTags: 'Curry,Meat',
    strYoutube: 'https://www.youtube.com/watch?v=r7SYVSG5nxo',
    strIngredient1: 'Cashew nuts',
    strIngredient2: 'Khus khus',
    strIngredient3: 'Cumin seeds',
    strIngredient4: 'Onions',
    strIngredient5: 'Ginger garlic paste',
    strIngredient6: 'Garlic',
    strIngredient7: 'Mint',
    strIngredient8: 'Cilantro',
    strIngredient9: 'Saffron',
    strIngredient10: 'Ghee',
    strIngredient11: 'Basmati rice',
    strIngredient12: 'Full fat yogurt',
    strIngredient13: 'Cumin Seeds',
    strIngredient14: 'Bay leaf',
    strIngredient15: 'Cinnamon',
    strIngredient16: 'Cloves',
    strIngredient17: 'Cardamom',
    strIngredient18: 'Lamb',
    strIngredient19: 'Red Chilli powder',
    strIngredient20: 'Biryani masala',
    strMeasure1: '12',
    strMeasure2: '½ tbsp',
    strMeasure3: '½ tbsp',
    strMeasure4: '3 sliced thinly',
    strMeasure5: '2 tsp',
    strMeasure6: '4 whole',
    strMeasure7: 'Leaves',
    strMeasure8: 'Leaves',
    strMeasure9: '½ tsp dissolved in ½ cup warm milk',
    strMeasure10: '2 tbsp',
    strMeasure11: '2 Cups',
    strMeasure12: '½ cup',
    strMeasure13: '1 tbsp',
    strMeasure14: '½',
    strMeasure15: '1 thin piece',
    strMeasure16: '3',
    strMeasure17: '2',
    strMeasure18: '1 lb',
    strMeasure19: '1 tsp',
    strMeasure20: '1 tbsp',
    strSource: 'http://www.relishthebite.com/restaurant-style-lamb-biryani/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52805.png',
    idCategory: '4',
    idIngredients: [
      '50',
      '188',
      '105',
      '227',
      '156',
      '149',
      '214',
      '83',
      '276',
      '153',
      '19',
      '147',
      '105',
      '20',
      '84',
      '87',
      '47',
      '191',
      '261',
      '28',
    ],
  },
  {
    idMeal: '53021',
    strMeal: 'Gołąbki (cabbage roll)',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Polish',
    strInstructions:
      'Bring a large pot of lightly salted water to a boil. Place cabbage head into water, cover pot, and cook until cabbage leaves are slightly softened enough to remove from head, 3 minutes. Remove cabbage from pot and let cabbage sit until leaves are cool enough to handle, about 10 minutes.\r\n\r\nRemove 18 whole leaves from the cabbage head, cutting out any thick tough center ribs. Set whole leaves aside. Chop the remainder of the cabbage head and spread it in the bottom of a casserole dish.\r\n\r\nMelt butter in a large skillet over medium-high heat. Cook and stir onion in hot butter until tender, 5 to 10 minutes. Cool.\r\n\r\nStir onion, beef, pork, rice, garlic, 1 teaspoon salt, and 1/4 teaspoon pepper together in a large bowl.\r\n\r\nPreheat oven to 350 degrees F (175 degrees C).\r\n\r\nPlace about 1/2 cup beef mixture on a cabbage leaf. Roll cabbage around beef mixture, tucking in sides to create an envelope around the meat. Repeat with remaining leaves and meat mixture. Place cabbage rolls in a layer atop the chopped cabbage in the casserole dish; season rolls with salt and black pepper.\r\n\r\nWhisk tomato soup, tomato juice, and ketchup together in a bowl. Pour tomato soup mixture over cabbage rolls and cover dish wish aluminum foil.\r\n\r\nBake in the preheated oven until cabbage is tender and meat is cooked through, about 1 hour.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/q8sp3j1593349686.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=rBrTkDdoPYg',
    strIngredient1: 'Cabbage',
    strIngredient2: 'Butter',
    strIngredient3: 'Onion',
    strIngredient4: 'Ground Beef',
    strIngredient5: 'Ground Pork',
    strIngredient6: 'Rice',
    strIngredient7: 'Garlic',
    strIngredient8: 'Salt',
    strIngredient9: 'Black Pepper',
    strIngredient10: 'Tomato Puree',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1',
    strMeasure2: '2 tbs',
    strMeasure3: '1 chopped',
    strMeasure4: '1 lb',
    strMeasure5: '1/2 lb',
    strMeasure6: '1 1/2 cups ',
    strMeasure7: '1 tsp ',
    strMeasure8: '1 tsp ',
    strMeasure9: '1/4 tsp',
    strMeasure10: '3 cans',
    strMeasure11: ' ',
    strMeasure12: ' ',
    strMeasure13: ' ',
    strMeasure14: ' ',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.allrecipes.com/recipe/234975/golabki-stuffed-cabbage-rolls/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53021.png',
    idCategory: '1',
    idIngredients: [
      '440',
      '41',
      '364',
      '512',
      '569',
      '268',
      '149',
      '281',
      '29',
      '316',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '52930',
    strMeal: 'Pate Chinois',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Canadian',
    strInstructions:
      'In a large pot of salted water, cook the potatoes until they are very tender. Drain.\r\nWith a masher, coarsely crush the potatoes with at least 30 ml (2 tablespoons) of butter. With an electric mixer, purée with the milk. Season with salt and pepper. Set aside.\r\nWith the rack in the middle position, preheat the oven to 190 °C (375 °F).\r\nIn a large skillet, brown the onion in the remaining butter. Add the meat and cook until golden brown. Season with salt and pepper. Remove from the heat.\r\nLightly press the meat at the bottom of a 20-cm (8-inch) square baking dish. Cover with the corn and the mashed potatoes. Sprinkle with paprika and parsley.\r\nBake for about 30 minutes. Finish cooking under the broiler. Let cool for 10 minutes.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/yyrrxr1511816289.jpg',
    strTags: 'MainMeal,Alcoholic',
    strYoutube: 'https://www.youtube.com/watch?v=QRFqnLkEv3I',
    strIngredient1: 'Potatoes',
    strIngredient2: 'Butter',
    strIngredient3: 'Milk',
    strIngredient4: 'Minced Beef',
    strIngredient5: 'Onion',
    strIngredient6: 'Creamed Corn',
    strIngredient7: 'Paprika',
    strIngredient8: 'Parsley',
    strIngredient9: 'Salt',
    strIngredient10: 'Pepper',
    strIngredient11: '',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '4 cups ',
    strMeasure2: '60ml',
    strMeasure3: '½ cup ',
    strMeasure4: '450g',
    strMeasure5: '1 finely chopped ',
    strMeasure6: '500ml',
    strMeasure7: 'to taste',
    strMeasure8: 'to taste',
    strMeasure9: 'Dash',
    strMeasure10: 'Dash',
    strMeasure11: '',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource:
      'https://www.ricardocuisine.com/en/recipes/5541-pate-chinois-shepherd--s-pie-',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '52930.png',
    idCategory: '1',
    idIngredients: [
      '253',
      '41',
      '211',
      '387',
      '364',
      '503',
      '232',
      '237',
      '281',
      '244',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    idMeal: '53042',
    strMeal: 'Portuguese prego with green piri-piri',
    strDrinkAlternate: null,
    strCategory: 'Beef',
    strArea: 'Portuguese',
    strInstructions:
      'STEP 1\r\n\r\nRub the garlic over the steaks then put in a sandwich bag and tip in the olive oil, sherry vinegar and parsley stalks. Smoosh everything together, then use a rolling pin to bash the steaks a few times. Leave for 1-2 hours.\r\n\r\nSTEP 2\r\n\r\nTo make the sauce, put all the ingredients into a blender with 1 tbsp water and whizz until as smooth as possible. This will make more than you’ll need for the recipe but will keep for a week in an airtight jar.\r\n\r\nSTEP 3\r\n\r\nHeat a griddle or frying pan to high. Brush away the garlic and parsley stalks from the steaks and season well. Sear the steaks for 2 minutes on each side then rest on a plate. Put the ciabatta halves onto the plate, toasted-side down, to soak up any juices.\r\n\r\nSTEP 4\r\n\r\nSlice the steaks then stuff into the rolls with the green sauce and rocket.',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg',
    strTags: null,
    strYoutube: 'https://www.youtube.com/watch?v=FbIKfcDEPLA',
    strIngredient1: 'Garlic',
    strIngredient2: 'Beef Fillet',
    strIngredient3: 'Olive Oil',
    strIngredient4: 'Vinegar',
    strIngredient5: 'Parsley',
    strIngredient6: 'Ciabatta',
    strIngredient7: 'Rocket',
    strIngredient8: 'Basil Leaves',
    strIngredient9: 'Parsley',
    strIngredient10: 'Jalapeno',
    strIngredient11: 'Vinegar',
    strIngredient12: 'Spring Onions',
    strIngredient13: 'Garlic',
    strIngredient14: 'Caster Sugar',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '1 clove',
    strMeasure2: '2 small',
    strMeasure3: '2 tbs',
    strMeasure4: '1 tbs',
    strMeasure5: 'Leaves',
    strMeasure6: '2',
    strMeasure7: '2 handfulls',
    strMeasure8: 'Small bunch',
    strMeasure9: 'Small bunch',
    strMeasure10: '1',
    strMeasure11: '1 tbs',
    strMeasure12: '2 chopped',
    strMeasure13: '1/2 ',
    strMeasure14: '1/2 tsp',
    strMeasure15: ' ',
    strMeasure16: ' ',
    strMeasure17: ' ',
    strMeasure18: ' ',
    strMeasure19: ' ',
    strMeasure20: ' ',
    strSource:
      'https://www.olivemagazine.com/recipes/meat-and-poultry/portuguese-prego-with-green-piri-piri/',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
    strStorageimg: '53042.png',
    idCategory: '1',
    idIngredients: [
      '149',
      '24',
      '224',
      '332',
      '237',
      '606',
      '273',
      '18',
      '237',
      '184',
      '332',
      '301',
      '149',
      '52',
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
];
